name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          zip -r -X resources.zip assets pack.mcmeta pack.png

      - name: Calculate hash of resource.zip
        id: calculate-hash
        run: |
          hash=$(sha1sum resources.zip | awk '{ print $1 }')
          echo "hash=$hash" >> "$GITHUB_ENV"
          echo "$hash" > hash.txt

      - name: Commit and push hash.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add hash.txt
          git commit -m "Update hash.txt with new hash"
          git push origin main:hash --force

      - name: latest-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: "resources.zip"

      - name: Invoke release hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "hash": "${{ env.hash }}" }'
